environment:
  node_pre_gyp_accessKeyId:
    secure: tRTeycc9QsAhb1FCXkU6JQwEyr5wu7pz9YtMsJvDFsA=
  node_pre_gyp_secretAccessKey:
    secure: K8M62m8ynQah8FRcnHyoetn5X0XzXdfwLrf7iWiM9A3SyX1TF1xy+auYQF/Nu48B
  matrix:
    - NODE_VERSION: "7.6.0"
      platform: x64
      npm_config_runtime: "node"
      npm_config_target: "7.6.0"

    - NODE_VERSION: "7.6.0"
      platform: x64
      npm_config_target: "1.6.6"
      npm_config_disturl: "https://atom.io/download/electron"
      npm_config_runtime: "electron"
      npm_config_build_from_source: "true"

    - NODE_VERSION: "7.6.0"
      platform: x86
      npm_config_runtime: "node"
      npm_config_target: "7.6.0"

    - NODE_VERSION: "7.6.0"
      platform: x86
      npm_config_target: "1.6.6"
      npm_config_disturl: "https://atom.io/download/electron"
      npm_config_runtime: "electron"
      npm_config_build_from_source: "true"

os: Visual Studio 2015

install:
  - ps: Install-Product node $env:NODE_VERSION $env:PLATFORM
  - npm install --build-from-source
  - node .\node_modules\.bin\node-pre-gyp package --runtime=$npm_config_runtime --target=$npm_config_target
  - node .\node_modules\.bin\node-pre-gyp publish --runtime=$npm_config_runtime --target=$npm_config_target

build: OFF
test: OFF
deploy: OFF
